apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  endpoints:
  - port: test
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'probe_failed_due_to_regex'
      action: drop